port: 8080
services:
    frontend:
        endpoint: '/'
        host: 'http://127.0.0.1:3000'
    api:
        endpoint: '/api'
        host: 'http://127.0.0.1:3001'
    chat:
        endpoint: '/api/chat'
        host: 'http://127.0.0.1:3002'
    filestore:
        endpoint: '/api/filestore'
        host: 'http://127.0.0.1:3003'